GRAMMAR_RULES = [
    (r'\bI\s+does\b',     "I do",     "'does' is wrong with 'I' → use 'do'"),
    (r'\bI\s+has\b',      "I have",   "'has' is wrong with 'I' → use 'have'"),
    (r'\bI\s+is\b',       "I am",     "'is' is wrong with 'I' → use 'am'"),
    (r'\bI\s+are\b',      "I am",     "'are' is wrong with 'I' → use 'am'"),

    (r'\bYou\s+does\b',   "You do",   "'does' is wrong with 'You' → use 'do'"),
    (r'\bWe\s+does\b',    "We do",    "'does' is wrong with 'We' → use 'do'"),
    (r'\bThey\s+does\b',  "They do",  "'does' is wrong with 'They' → use 'do'"),
    (r'\bYou\s+has\b',    "You have", "'has' is wrong with 'You' → use 'have'"),
    (r'\bWe\s+has\b',     "We have",  "'has' is wrong with 'We' → use 'have'"),
    (r'\bThey\s+has\b',   "They have","'has' is wrong with 'They' → use 'have'"),
    (r'\bYou\s+is\b',     "You are",  "'is' is wrong with 'You' → use 'are'"),
    (r'\bWe\s+is\b',      "We are",   "'is' is wrong with 'We' → use 'are'"),
    (r'\bThey\s+is\b',    "They are", "'is' is wrong with 'They' → use 'are'"),

    (r'\bHe\s+do\b',      "He does",  "'do' is wrong with 'He' → use 'does'"),
    (r'\bShe\s+do\b',     "She does", "'do' is wrong with 'She' → use 'does'"),
    (r'\bIt\s+do\b',      "It does",  "'do' is wrong with 'It' → use 'does'"),
    (r'\bHe\s+have\b',    "He has",   "'have' is wrong with 'He' → use 'has'"),
    (r'\bShe\s+have\b',   "She has",  "'have' is wrong with 'She' → use 'has'"),
    (r'\bIt\s+have\b',    "It has",   "'have' is wrong with 'It' → use 'has'"),
    (r'\bHe\s+are\b',     "He is",    "'are' is wrong with 'He' → use 'is'"),
    (r'\bShe\s+are\b',    "She is",   "'are' is wrong with 'She' → use 'is'"),
    (r'\bIt\s+are\b',     "It is",    "'are' is wrong with 'It' → use 'is'"),

    (r'\bThis\s+are\b',    "This is",   "'are' is wrong with 'This' → use 'is'"),
    (r'\bThat\s+are\b',    "That is",   "'are' is wrong with 'That' → use 'is'"),
    (r'\bThis\s+have\b',   "This has",  "'have' is wrong with 'This' → use 'has'"),
    (r'\bThat\s+have\b',   "That has",  "'have' is wrong with 'That' → use 'has'"),
    (r'\bThis\s+do\b',     "This does", "'do' is wrong with 'This' → use 'does'"),
    (r'\bThat\s+do\b',     "That does", "'do' is wrong with 'That' → use 'does'"),

    (r'\bThese\s+is\b',    "These are", "'is' is wrong with 'These' → use 'are'"),
    (r'\bThose\s+is\b',    "Those are", "'is' is wrong with 'Those' → use 'are'"),
    (r'\bThese\s+has\b',   "These have","'has' is wrong with 'These' → use 'have'"),
    (r'\bThose\s+has\b',   "Those have","'has' is wrong with 'Those' → use 'have'"),
    (r'\bThese\s+does\b',  "These do",  "'does' is wrong with 'These' → use 'do'"),
    (r'\bThose\s+does\b',  "Those do",  "'does' is wrong with 'Those' → use 'do'"),

    (r'\ba\s+([aeiou])',   "an \\1",    "Use 'an' before vowel sounds"),
    (r'\ban\s+([bcdfghjklmnpqrstvwxyz])', "a \\1", "Use 'a' before consonant sounds"),

    (r'\bhim\s+and\s+me\b',     "him and I",   "After 'and' in subject: use 'I' not 'me'"),
    (r'\bme\s+and\s+him\b',     "I and him",   "Use 'I' at start (subject position)"),
    (r'\bbetween\s+you\s+and\s+I\b', "between you and me", "'between' uses objective case: 'me'"),

    (r'\bmore\s+(?:big|small|short|tall|good|bad|fast|slow|happy|sad)\b', None, 
     "Use comparative form: 'bigger', 'smaller', 'better', 'worse', etc."),
    (r'\bmost\s+(?:big|small|short|tall|good|bad|fast|slow|happy|sad)\b', None,
     "Use superlative form: 'biggest', 'smallest', 'best', 'worst', etc."),
    (r'\bmore\s+better\b', "better", "Don't use 'more' + comparative form"),
    (r'\bmost\s+best\b',   "best",   "Don't use 'most' + superlative form"),

    (r'\bdon\'t\s+\w+\s+no\b', None, "Double negative: use 'don't' OR 'no', not both"),
    (r'\bcan\'t\s+\w+\s+nothing\b', None, "Double negative: avoid both negatives"),
    (r'\bnot\s+\w+\s+no\b', None, "Double negative: use only one negative word"),

    (r'\bI\s+will\s+goes\b', "I will go", "Future: 'will goes' → 'will go'"),
    (r'\bwill\s+have\s+go\b', "will have gone", "Use past participle after 'have': 'gone'"),
    (r'\byesterday\s+\w+\s+will\b', None, "'yesterday' cannot use 'will'"),
    (r'\bnext\s+\w+\s+(?:went|was)\b', None, "Future time needs future tense"),
    (r'\bI\s+have\s+went\b', "I have gone", "Use 'have gone' not 'have went'"),
    (r'\bI\s+have\s+saw\b', "I have seen", "Use 'have seen' not 'have saw'"),
    (r'\bI\s+have\s+took\b', "I have taken", "Use 'have taken' not 'have took'"),
    (r'\bI\s+have\s+gave\b', "I have given", "Use 'have given' not 'have gave'"),

    (r'\bif\s+\w+\s+will\b', None, "In 'if' clause: use present tense, not 'will'"),

    (r'\bwant\s+\w+ing\b', None, "'want' uses infinitive: 'want to go'"),
    (r'\bstop\s+to\s+\w+ing\b', None, "'stop' uses gerund: 'stop going'"),
    (r'\bkeep\s+to\s+\w+ing\b', None, "'keep' uses gerund: 'keep going'"),

    (r'\balways\s+(?:am|is|are|was|were)\b', None, "Adverb of frequency: place AFTER 'be' verb"),
    (r'\bnever\s+(?:am|is|are|was|were)\b', None, "Adverb of frequency: place AFTER 'be' verb"),
    (r'\boften\s+(?:am|is|are|was|were)\b', None, "Adverb of frequency: place AFTER 'be' verb"),

    (r'\byou\s+can\s+help\?', "Can you help?", "Questions: invert auxiliary and subject"),
    (r'\bwhat\s+you\s+(?:doing|do)\b', None, "Questions: 'What are you doing?' → invert"),

    (r'\baccording\s+with\b', "according to", "Use 'according to'"),
    (r'\bdepend\s+of\b', "depend on", "Use 'depend on'"),
    (r'\bfocus\s+in\b', "focus on", "Use 'focus on'"),
    (r'\binterested\s+on\b', "interested in", "Use 'interested in'"),
    (r'\bdifferent\s+than\b', "different from", "Use 'different from'"),
    (r'\bsimilar\s+with\b', "similar to", "Use 'similar to'"),

    (r'(?:^|\s)(i)(?:\s|$)', " I ", "First-person pronoun 'I' must be capitalized"),
    (r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december)\b', None, 
     "Months must be capitalized"),
    (r'\b(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b', None,
     "Days of week must be capitalized"),

    (r'\bmuch\s+(?:students|people|books|chairs)\b', None, "Use 'many' with countable nouns"),
    (r'\bfew\s+(?:water|information|advice|luggage|furniture)\b', "little", 
     "Use 'little' with uncountable nouns"),
    (r'\bmany\s+(?:water|information|advice|luggage|furniture)\b', "much",
     "Use 'much' with uncountable nouns"),

    (r'\bsince\s+\w+\s+years\b', "for ... years", "Use 'for' with duration"),
]
